version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "builld package"
      - zip -r lambda_function.zip .  # Packages the code
artifacts:
  files:
    - lambda_function.zip  
